ci:
  autofix_commit_msg: |
    Autofix formatting from pre-commit hooks

  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

default_language_version:
  python: python3

repos:
  # General sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  # Ruff (lint + fix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix]
        types: [python]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.4
    hooks:
      - id: uv-lock

  # TODO: Add pyright

  # Black (formatting)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Jupyter Notebook support
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
      - id: nbqa-black
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black-jupyter
        language_version: python3

# TODO: Docstring Formatter doesn't take Python 3.14, only previous versions
